# CMake generated Testfile for 
# Source directory: B:/Capstone/Digital-Twin-CS_Capstone/vcpkg/buildtrees/libbson/src/1.24.3-34dd83f208.clean
# Build directory: B:/Capstone/Digital-Twin-CS_Capstone/vcpkg/buildtrees/libbson/x64-windows-dbg
# 
# This file includes the relevant testing commands required for 
# testing this directory and lists subdirectories to be tested as well.
add_test(mongoc/fixtures/fake_imds/start "C:/ProgramData/anaconda3/python.exe" "-u" "--" "B:/Capstone/Digital-Twin-CS_Capstone/vcpkg/buildtrees/libbson/src/1.24.3-34dd83f208.clean/build/proc-ctl.py" "start" "--ctl-dir=B:/Capstone/Digital-Twin-CS_Capstone/vcpkg/buildtrees/libbson/x64-windows-dbg/.ctl" "--cwd=B:/Capstone/Digital-Twin-CS_Capstone/vcpkg/buildtrees/libbson/x64-windows-dbg" "--spawn-wait=0.2" "--" "C:/ProgramData/anaconda3/python.exe" "-u" "--" "B:/Capstone/Digital-Twin-CS_Capstone/vcpkg/buildtrees/libbson/src/1.24.3-34dd83f208.clean/build/bottle.py" "fake_kms_provider_server:kms_provider" "--bind" "localhost:14987")
set_tests_properties(mongoc/fixtures/fake_imds/start PROPERTIES  FIXTURES_SETUP "mongoc/fixtures/fake_imds" _BACKTRACE_TRIPLES "B:/Capstone/Digital-Twin-CS_Capstone/vcpkg/buildtrees/libbson/src/1.24.3-34dd83f208.clean/build/cmake/TestFixtures.cmake;29;add_test;B:/Capstone/Digital-Twin-CS_Capstone/vcpkg/buildtrees/libbson/src/1.24.3-34dd83f208.clean/build/cmake/TestFixtures.cmake;42;mongo_define_subprocess_fixture;B:/Capstone/Digital-Twin-CS_Capstone/vcpkg/buildtrees/libbson/src/1.24.3-34dd83f208.clean/build/cmake/TestFixtures.cmake;0;;B:/Capstone/Digital-Twin-CS_Capstone/vcpkg/buildtrees/libbson/src/1.24.3-34dd83f208.clean/CMakeLists.txt;333;include;B:/Capstone/Digital-Twin-CS_Capstone/vcpkg/buildtrees/libbson/src/1.24.3-34dd83f208.clean/CMakeLists.txt;0;")
add_test(mongoc/fixtures/fake_imds/stop "C:/ProgramData/anaconda3/python.exe" "-u" "--" "B:/Capstone/Digital-Twin-CS_Capstone/vcpkg/buildtrees/libbson/src/1.24.3-34dd83f208.clean/build/proc-ctl.py" "stop" "--ctl-dir=B:/Capstone/Digital-Twin-CS_Capstone/vcpkg/buildtrees/libbson/x64-windows-dbg/.ctl" "--if-not-running=ignore")
set_tests_properties(mongoc/fixtures/fake_imds/stop PROPERTIES  FIXTURES_CLEANUP "mongoc/fixtures/fake_imds" _BACKTRACE_TRIPLES "B:/Capstone/Digital-Twin-CS_Capstone/vcpkg/buildtrees/libbson/src/1.24.3-34dd83f208.clean/build/cmake/TestFixtures.cmake;35;add_test;B:/Capstone/Digital-Twin-CS_Capstone/vcpkg/buildtrees/libbson/src/1.24.3-34dd83f208.clean/build/cmake/TestFixtures.cmake;42;mongo_define_subprocess_fixture;B:/Capstone/Digital-Twin-CS_Capstone/vcpkg/buildtrees/libbson/src/1.24.3-34dd83f208.clean/build/cmake/TestFixtures.cmake;0;;B:/Capstone/Digital-Twin-CS_Capstone/vcpkg/buildtrees/libbson/src/1.24.3-34dd83f208.clean/CMakeLists.txt;333;include;B:/Capstone/Digital-Twin-CS_Capstone/vcpkg/buildtrees/libbson/src/1.24.3-34dd83f208.clean/CMakeLists.txt;0;")
subdirs("src/common")
subdirs("src/libbson")
